package models

import "time"

// CreateComplaintRequest represents the request to create a new complaint
type CreateComplaintRequest struct {
	Title              string   `json:"title" validate:"required,max=500"`
	Description        string   `json:"description" validate:"required"`
	Category           *string  `json:"category,omitempty"`
	LocationID         int64    `json:"location_id" validate:"required"`
	Latitude           *float64 `json:"latitude,omitempty"`
	Longitude          *float64 `json:"longitude,omitempty"`
	Pincode            *string  `json:"pincode,omitempty"` // PIN code for abuse prevention
	Priority           *string  `json:"priority,omitempty"` // "low", "medium", "high", "urgent"
	PublicConsentGiven bool     `json:"public_consent_given"`
	AttachmentURLs     []string `json:"attachment_urls,omitempty"` // Pre-uploaded file URLs
	DeviceFingerprint  *string  `json:"device_fingerprint,omitempty"` // Generated by backend, not from frontend
}

// CreateComplaintResponse represents the response after creating a complaint
type CreateComplaintResponse struct {
	ComplaintID          int64  `json:"complaint_id"`
	ComplaintNumber      string `json:"complaint_number"`
	Status               string `json:"status"`
	Message              string `json:"message"`
	AssignedDepartmentID *int64 `json:"assigned_department_id,omitempty"` // For admin visibility
}

// ComplaintDetailResponse represents a complaint with full details (citizen view)
// ComplaintSummary represents a summary of a complaint for list views
type ComplaintSummary struct {
	ComplaintID    int64     `json:"complaint_id"`
	ComplaintNumber string   `json:"complaint_number"`
	Title          string    `json:"title"`
	CurrentStatus  string    `json:"current_status"`
	Priority       string    `json:"priority"`
	CreatedAt      time.Time `json:"created_at"`
	SupporterCount int       `json:"supporter_count"`
}

type ComplaintDetailResponse struct {
	ComplaintID          int64     `json:"complaint_id"`
	ComplaintNumber      string    `json:"complaint_number"`
	Title                string    `json:"title"`
	Description          string    `json:"description"`
	Category             *string   `json:"category,omitempty"`
	LocationID           int64     `json:"location_id"`
	Latitude             *float64  `json:"latitude,omitempty"`
	Longitude            *float64  `json:"longitude,omitempty"`
	AssignedDepartmentID *int64    `json:"assigned_department_id,omitempty"`
	AssignedOfficerID    *int64    `json:"assigned_officer_id,omitempty"`
	CurrentStatus        string    `json:"current_status"`
	Priority             string    `json:"priority"`
	IsPublic             bool      `json:"is_public"`
	SupporterCount       int       `json:"supporter_count"`
	ResolvedAt           *time.Time `json:"resolved_at,omitempty"`
	ClosedAt             *time.Time `json:"closed_at,omitempty"`
	CreatedAt            time.Time `json:"created_at"`
	Attachments          []AttachmentInfo `json:"attachments,omitempty"`
}

// AttachmentInfo represents attachment information in responses
type AttachmentInfo struct {
	AttachmentID int64  `json:"attachment_id"`
	FileName     string `json:"file_name"`
	FilePath     string `json:"file_path"`
	FileType     *string `json:"file_type,omitempty"`
	FileSize     *int64 `json:"file_size,omitempty"`
	IsPublic     bool   `json:"is_public"`
}

// StatusTimelineResponse represents the status timeline for a complaint
type StatusTimelineResponse struct {
	ComplaintID int64              `json:"complaint_id"`
	ComplaintNumber string          `json:"complaint_number"`
	Timeline    []StatusTimelineEntry `json:"timeline"`
}

// StatusTimelineEntry represents a single status change entry
type StatusTimelineEntry struct {
	HistoryID            int64     `json:"history_id"`
	OldStatus            *string   `json:"old_status,omitempty"`
	NewStatus            string    `json:"new_status"`
	ChangedByType        string    `json:"changed_by_type"`
	ChangedByUserID      *int64    `json:"changed_by_user_id,omitempty"`
	ChangedByOfficerID   *int64    `json:"changed_by_officer_id,omitempty"`
	AssignedDepartmentID *int64    `json:"assigned_department_id,omitempty"`
	AssignedOfficerID    *int64    `json:"assigned_officer_id,omitempty"`
	Notes                *string   `json:"notes,omitempty"`
	CreatedAt            time.Time `json:"created_at"`
}

// UpdateStatusRequest represents the request to update complaint status (internal use)
type UpdateStatusRequest struct {
	NewStatus            string  `json:"new_status" validate:"required"`
	AssignedDepartmentID *int64  `json:"assigned_department_id,omitempty"`
	AssignedOfficerID    *int64  `json:"assigned_officer_id,omitempty"`
	Notes                *string `json:"notes,omitempty"`
}

// UpdateStatusResponse represents the response after updating status
type UpdateStatusResponse struct {
	ComplaintID     int64  `json:"complaint_id"`
	ComplaintNumber string `json:"complaint_number"`
	OldStatus       string `json:"old_status"`
	NewStatus       string `json:"new_status"`
	Message         string `json:"message"`
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
	Code    int    `json:"code,omitempty"`
}

// AuthorityUpdateStatusRequest represents authority's status update request
type AuthorityUpdateStatusRequest struct {
	NewStatus string `json:"new_status" validate:"required"` // under_review, in_progress, resolved, closed
	Reason    string `json:"reason" validate:"required"`      // Required reason text
}

// AuthorityAddNoteRequest represents request to add internal note
type AuthorityAddNoteRequest struct {
	NoteText string `json:"note_text" validate:"required"`
}

// AuthorityNoteResponse represents response after adding note
type AuthorityNoteResponse struct {
	NoteID      int64  `json:"note_id"`
	ComplaintID int64  `json:"complaint_id"`
	Message     string `json:"message"`
}

// AuthorityNote represents an internal note added by authority
type AuthorityNote struct {
	NoteID      int64     `json:"note_id"`
	ComplaintID int64     `json:"complaint_id"`
	OfficerID   int64     `json:"officer_id"`
	NoteText    string    `json:"note_text"`
	CreatedAt   time.Time `json:"created_at"`
}
